settings:
  coming_soon_window_days: 90
  horizon_window_days: 9999
  youtube_update:
    mode: "multiple"   # single | multiple | playlist | all
    single:
      youtube_id: "r16qSkxEcI4"
    multiple:
      youtube_ids:
        - kyNVmUkFmXQ
        - 3zemHQQc4So
        - r16qSkxEcI4
        - gDkCGYOpWU0
        - oMSIQ5Gv2ZI
    playlist:
      playlist_id: "pop-instrumental-horizon-sound-instrumentals"
